---
title: "GloBAM Data Management Plan"
author:
- Peter Desmet
- Cecilia Nilsson
- Adriaan Dokter
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
github-repo: "enram/globam-dmp"
output:
  bookdown::gitbook:
    split_by: rmd
    df_print: kable
    config:
      toc:
        collapse: section
      search: yes
      edit: https://github.com/enram/globam-dmp/blob/master/%s
      download: ["pdf"]
      sharing:
        facebook: no
        twitter: yes
        all: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, # Exclude code chunks from output
  warning = FALSE,
  message = FALSE
)

# Load required libraries
library(tidyverse)      # To do data science
library(tidylog)        # To provide feedback on dplyr functions
library(lubridate)      # To work with dates
library(here)           # To find files
library(janitor)        # To add totals to tables
library(jsonlite)       # To read json
```

<!-- References used in this document -->

[enram-repo]: http://enram.github.io/data-repository/
[oscibio]: https://twitter.com/oscibio
[nilsson_2018_zenodo]: https://doi.org/10.5281/zenodo.1172801
[cc0]: https://creativecommons.org/publicdomain/zero/1.0/

# Colophon {-}

Distributions of this data management plan:

- Latest version (website): <https://enram.github.io/globam-dmp/>
- Latest version (pdf): <https://enram.github.io/globam-dmp/globam-dmp.pdf>
- Periodically archived version (pdf): _to be deposited on Zenodo.org_

Suggested citation for the latest version:

```{r}
# Read metadata from index.Rmd
frontmatter <- rmarkdown::yaml_front_matter(here("index.Rmd"))

# Split authors in form Last F, Last F
authors <- map(frontmatter$author, function(x) {
  split_name <- str_split(x, pattern = " ")[[1]]
  paste(split_name[2], str_sub(split_name[1], 1, 1))
})

# Create citation
citation <- paste0(
  paste(authors, collapse = ", "),
  " (",
  year(Sys.Date()),
  ") ",
  frontmatter$title,
  ". Version ",
  Sys.Date(),
  ". https://enram.github.io/globam-dmp/"
)
```

> `r citation`

All versions are licensed under a [Creative Commons Attribution License (CC BY 4.0)](http://creativecommons.org/licenses/by/4.0/).
