# Other external data

This chapter describes other external data sources required by GloBAM.

## Wind/weather data

### Users

Needed for at least WP3, WP4, WP5 and maybe WP2. The type of weather data (wind, precipitation) will differ between analyses.

### Sources

- World: to be defined
- US: [NCEP/NCAR Reanalysis data from NOAA](https://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis.html) has been used before.
- Europe: to be defined, see https://github.com/enram/globam-dmp/issues/21

## Land use

To be defined, see https://github.com/enram/globam-dmp/issues/25

## Artificial light

### Users

Needed for WP3.

### Sources

[Visible Infrared Imaging Radiometer Suite (VIIRS) Day/Night Band](https://ngdc.noaa.gov/eog/viirs/download_dnb_composites.html) provided by NOAA. See that page for a description, filenaming conventions, data types/formats and providing credit.

We may also use the new [Black Marble product](https://viirsland.gsfc.nasa.gov/Products/NASA/BlackMarble.html) from NASA (not yet released).

## Wind energy installations

### Users

Needed for WP4 (Judy Shamoun-Baranes).

### Sources

Depends on the exact research questions and what is available. Will be updated in DMP once known.
