# (PART\*) Publishing & preservation {-}

# Open data

This chapter describes how we will publish data of long term value that GloBAM will use and generate.

## Data

The data of long term value that GloBAM will generate are the `vp`/`vpts` data for Europe and the United States (see the respective chapters).

## Repository

As there is no specific research repository for `vp`/`vpts` data, we will publish these data on the general research repository [Zenodo](https://zenodo.org). This has already been done for [Nilsson et al. 2018][nilsson_2018_zenodo] and will likely look similar for data published for GloBAM. Data packages published on Zenodo are assigned a Digital Object Identifier (DOI) for easier referencing (both a generic one and one for each updated version).

## License

Data will be published under a [Creative Commons Zero waiver][cc0].

## Metadata

Data will be documented with metadata describing the contributors, provenance, resolution, temporal and spatial coverage, and how to use these with open source software developed or contributed to by GloBAM.

## Standards

Data will be kept in their source format, i.e. the ODIM bird profile format specification (see \@ref(vp-format)).

## Frequency

Data will be published on Zenodo every two years. Closer to real-time data are already publicly available in the [ENRAM data repository][enram-repo].
