---
title: "Create BALTRAD file listing summary"
author: "Cecilia Nilsson, Peter Desmet"
date: "`r Sys.Date()`"
output: html_document
params:
  create_baltrad_coverage: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries:

```{r}
library(tidyverse)
library(here)
```

## Create pvol coverage from BALTRAD file listing

Read data:

```{r read_baltrad_filelisting, eval = params$create_baltrad_coverage}
baltrad_files <- read_csv("~/Downloads/baltrad/baltrad_filelisting.csv", col_names = FALSE)
```

Parse file names into columns:

```{r eval = params$create_baltrad_coverage}
baltrad_files <-
  baltrad_files %>%
  mutate(
    radar = str_sub(X1, 1, 5),
    date = paste(str_sub(X1, 12, 15), str_sub(X1, 16, 17), str_sub(X1, 18, 19), sep = "-"),
    hour = str_sub(X1, 21, 22),
    hex = str_extract(X1, "\\dx\\d")
  )
```

Summarize by `radar` and `date`, calculate number of unique hours, files and listed hex values:

```{r eval = (params$create_baltrad_coverage)}
baltrad_coverage <-
  baltrad_files %>%
  group_by(
    radar,
    date
  ) %>%
  summarize(
    hours = n_distinct(hour),
    files = n(),
    hex = paste(unique(sort(hex)), collapse = "|"), # Sort will also remove NA values
  ) %>%
  arrange(
    radar,
    date
  )
```

Save file:

```{r eval = (params$create_baltrad_coverage)}
write_csv(baltrad_coverage, here::here("data", "baltrad_pvol_coverage.csv"), na = "")
```

```{r}
```
